routes/web.php
<?php

use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Backend\PostController;
use App\Http\Controllers\Backend\UserController;
use App\Http\Controllers\Backend\CategoryController;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Frontend\FrontendController;
use App\Http\Controllers\Backend\MudVulcanoController;
use App\Http\Controllers\Backend\MudVulcanoImageController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', [LoginController::class, 'index'])->name('login');
Route::post('/login', [LoginController::class, 'login'])->name('login');

Route::prefix('admin')->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('category', CategoryController::class);
    Route::resource('users', UserController::class);
    Route::resource('mud-vulcano', MudVulcanoController::class);
    Route::get('mud-vulcano/{id}/images', [MudVulcanoImageController::class, 'index'])->name('mud-vulcano.images');
    Route::get('mud-vulcano/{id}/images/create', [MudVulcanoImageController::class, 'create'])->name('mud-vulcano.images.create');
    Route::post('mud-vulcano/{id}/images', [MudVulcanoImageController::class, 'store'])->name('mud-vulcano.images.store');
    Route::delete('mud-vulcano/{id}/images', [MudVulcanoImageController::class, 'destroy'])->name('mud-vulcano.images.destroy');

    Route::resource('post', PostController::class);
    Route::put('post/publish/{id}', [PostController::class, 'publish'])->name('post.publish');
    Route::put('post/unpublish/{id}', [PostController::class, 'unpublish'])->name('post.unpublish');
});
Route::get('/lang/{locale}', [HomeController::class, 'lang'])->name('lang');

Route::get('/', [FrontendController::class, 'index'])->name('home');
Route::get('/about', [FrontendController::class, 'about'])->name('about');
Route::get('/mud-vulcano', [FrontendController::class, 'mud_vulcano'])->name('mud-vulcano');
Route::get('/mud-vulcano-detail/{slug}', [FrontendController::class, 'mudvulcano_detail']);
Route::get('/post', [FrontendController::class, 'post'])->name('post');
Route::get('/post-detail/{slug}', [FrontendController::class, 'postdetail']);
// Route::get('/project-detail', [FrontendController::class, 'projectdetail']);
// Route::get('/blog', [FrontendController::class, 'blog'])->name('blog');
// Route::get('/contact', [FrontendController::class, 'contact'])->name('contact');
Route::post('/search', [FrontendController::class, 'search']);

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'slug',
        'thumbnail',
        'content',
        'user_id',
        'category_id',
        'published',
    ];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function setContentAttribute($value)
    {
        $this->attributes['content'] = $value;
    }
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Category;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use RealRashid\SweetAlert\Facades\Alert;
use Yajra\DataTables\Facades\DataTables;

class CategoryController extends Controller
{
    public function __construct()
    {
        $this->middleware(function ($request, $next) {
            if (session('success')) {
                Alert::success(session('success'));
            }

            if (session('error')) {
                Alert::error(session('error'));
            }

            return $next($request);
        });
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $categories = Category::with('posts')->get();
            return datatables()->of($categories)
                ->addIndexColumn()
                ->addColumn('action', function ($row) {
                    $btn = '<a href="' . route('category.edit', $row->id) . '" class="edit btn btn-primary btn-sm">Edit</a>';
                    //delete with form
                    if ($row->posts->count() == 0) {
                        $btn .= '<form action="' . route('category.destroy', $row->id) . '" method="POST" class="d-inline">
                                ' . csrf_field() . '
                                ' . method_field('DELETE') . '
                                <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm(`Anda Yakin ?`)">' . trans('translation.delete') . '</button>
                            </form>';
                    }
                    return $btn;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
        return view('backend.category.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $category = [
                'name' => $request->name,
                'slug' => Str::slug($request->name),
                'created_at' => now(),
                'updated_at' => now()
            ];

            Category::create($category);

            return redirect()->route('category.index')->with('success', trans('translation.success_message'));
        } catch (\Exception $e) {
            return redirect()->route('category.index')->with('error', trans('translation.error_message'));
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);
        return view('backend.category.create', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $category = [
                'name' => $request->name,
                'slug' => Str::slug($request->name),
                'updated_at' => now()
            ];

            Category::where('id', $id)->update($category);

            return redirect()->route('category.index')->with('success', trans('translation.success_update_message'));
        } catch (\Exception $e) {
            return redirect()->route('category.index')->with('error', trans('translation.error_update_message'));
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            Category::destroy($id);
            return redirect()->route('category.index')->with('success', trans('translation.success_delete_message'));
        } catch (\Exception $e) {
            return redirect()->route('category.index')->with('error', trans('translation.error_delete_message'));
        }
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Post;
use App\Models\User;
use App\Models\Category;
use App\Models\MudVulcano;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use RealRashid\SweetAlert\Facades\Alert;

class DashboardController extends Controller
{
    public function __construct()
    {
        $this->middleware(function ($request, $next) {
            if (session('success')) {
                Alert::success(session('success'));
            }

            if (session('error')) {
                Alert::error(session('error'));
            }

            return $next($request);
        });
    }
    //
    public function index()
    {
        //count category
        $category = Category::count();
        $post = Post::count();
        $user = User::count();
        $vulcano = MudVulcano::count();
        return view('backend.dashboard', compact('category', 'post', 'user', 'vulcano'));
    }
}

app/Http/Controllers/Backend/MudVulcanoController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\MudVulcano;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use App\Models\MudVulcanoImage;
use App\Http\Controllers\Controller;
use RealRashid\SweetAlert\Facades\Alert;

class MudVulcanoController extends Controller
{
    public function __construct()
    {
        $this->middleware(function ($request, $next) {
            if (session('success')) {
                Alert::success(session('success'));
            }

            if (session('error')) {
                Alert::error(session('error'));
            }

            return $next($request);
        });
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $mud = MudVulcano::with('user')->get();
            return datatables()->of($mud)
                ->addColumn('action', function ($mud) {
                    $button = '<a href="' . route('mud-vulcano.edit', $mud->id) . '" class="btn btn-primary btn-sm">Edit</a>';
                    $button .= '&nbsp;&nbsp;';
                    $button .= '<form action="' . route('mud-vulcano.destroy', $mud->id) . '" method="POST" class="d-inline">
                                ' . csrf_field() . '
                                ' . method_field('DELETE') . '
                                <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm(`Anda Yakin ?`)">' . trans('translation.delete') . '</button>
                            </form>';
                    $button .= '&nbsp;&nbsp;';
                    $button .= '<a href="' . route('mud-vulcano.images', $mud->id) . '" class="btn btn-success btn-sm">' . trans('translation.images') . '</a>';
                    return $button;
                })
                ->addColumn('thumbnail', function ($mud) {
                    $img = '<img src="' . asset($mud->thumbnail) . '" width="100px" height="100px">';
                    return $img;
                })
                ->rawColumns(['action', 'thumbnail'])
                ->addIndexColumn()
                ->make(true);
        }

        return view('backend.mud-vulcano.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.mud-vulcano.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            if ($request->file('thumbnail')) {
                $image = $request->file('thumbnail');
                $new_name = rand() . '.' . $image->getClientOriginalExtension();
                $image->move(public_path('img\vulcano\thumbnail'), $new_name);
            }

            $data = [
                'name' => $request->name,
                'slug' => Str::slug($request->name),
                'content' => $request->content,
                'user_id' => 1,
                'address' => $request->address,
                'latitude' => $request->latitude,
                'longitude' => $request->longitude,
                'thumbnail' => 'img/vulcano/thumbnail/' . $new_name,
                'created_at' => now(),
                'updated_at' => now()
            ];

            $mud = MudVulcano::create($data)->id;

            // dd($request->file('images'));
            foreach ($request->images as $image) {
                // dd($image);
                $new_name = rand() . '.' . $image->getClientOriginalExtension();
                $image->move(public_path('img\vulcano\images'), $new_name);

                $data = [
                    'mud_vulcano_id' => $mud,
                    'path_image' => 'img/vulcano/images/' . $new_name,
                    'created_at' => now(),
                    'updated_at' => now()
                ];

                MudVulcanoImage::create($data);
            }
            return redirect()->route('mud-vulcano.index')->with('success', trans('translation.success_message'));
        } catch (\Exception $e) {
            return redirect()->route('mud-vulcano.index')->with('error', trans('translation.error_message'));
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $vulcano = MudVulcano::find($id);
        return view('backend.mud-vulcano.create', compact('vulcano'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $data = [
                'name' => $request->name,
                'slug' => Str::slug($request->name),
                'content' => $request->content,
                'address' => $request->address,
                'latitude' => $request->latitude,
                'longitude' => $request->longitude,
                'updated_at' => now()
            ];
            $vulcano = MudVulcano::find($id);
            if ($request->file('thumbnail')) {
                if ($vulcano->thumbnail) {
                    unlink(public_path($vulcano->thumbnail));
                }
                $image = $request->file('thumbnail');
                $new_name = rand() . '.' . $image->getClientOriginalExtension();
                $image->move(public_path('img\vulcano\thumbnail'), $new_name);
                $data['thumbnail'] = 'img/vulcano/thumbnail/' . $new_name;
            }
            $vulcano->update($data);

            return redirect()->route('mud-vulcano.index')->with('success', trans('translation.success_update_message'));
        } catch (\Exception $e) {
            return redirect()->route('mud-vulcano.index')->with('error', trans('translation.error_update_message'));
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $vulcano = MudVulcano::find($id)->with('images')->first();
            if ($vulcano->thumbnail) {
                unlink(public_path($vulcano->thumbnail));
            }
            $imagesVulcano = MudVulcanoImage::where('mud_vulcano_id', $id)->get();
            if ($imagesVulcano) {
                foreach ($imagesVulcano as $image) {
                    unlink(public_path($image->path_image));
                }
            }
            $vulcano->images()->delete();
            $vulcano->delete();
            return redirect()->back()->with('success', trans('translation.success_message'));
        } catch (\Exception $e) {
            dd($e->getMessage());
        }
    }
}

resources/views/backend/post/create.blade.php
@extends('backend.layouts.app')
@section('title', @trans('translation.post'))
@section('header', @trans('translation.post'))
@section('style-extra')
    <link rel="stylesheet" href="{{ asset('backend/assets/modules/summernote/summernote-bs4.css') }}">
    <link rel="stylesheet" href="{{ asset('backend/assets/modules/codemirror/lib/codemirror.css') }}">
    <link rel="stylesheet" href="{{ asset('backend/assets/modules/codemirror/theme/duotone-dark.css') }}">
    <link rel="stylesheet" href="{{ asset('backend/assets/modules/jquery-selectric/selectric.css') }}">
@endsection
@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4>{{ isset($post) ? 'Edit' : trans('translation.create') }} @lang('translation.post')</h4>
                </div>
                <div class="card-body">
                    <form action="{{ isset($post) ? route('post.update', $post->id) : route('post.store') }}" method="post"
                        enctype="multipart/form-data">
                        {!! csrf_field() !!}
                        {{ isset($post) ? method_field('PUT') : '' }}
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">@lang('translation.title')</label>
                            <div class="col-sm-12 col-md-7">
                                <input type="text" class="form-control" name="title" value="{{ $post->title ?? '' }}"
                                    required>
                            </div>
                        </div>
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">@lang('translation.category')</label>
                            <div class="col-sm-12 col-md-7">
                                <select class="form-control selectric" name="category_id" required>
                                    <option value="">@lang('translation.select_category')</option>
                                    @foreach ($categories as $category)
                                        <option value="{{ $category->id }}"
                                            {{ isset($post) && $post->category_id == $category->id ? 'selected' : '' }}>
                                            {{ $category->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">@lang('translation.thumbnail')</label>
                            <div class="col-sm-12 col-md-7">
                                <input type="file" class="form-control" name="thumbnail" accept="image/*"
                                    {{ isset($post) ? '' : 'required' }}>
                            </div>
                        </div>
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">@lang('translation.content')</label>
                            <div class="col-sm-12 col-md-7">
                                <textarea class="summernote" name="content">{!! $post->content ?? '' !!}</textarea>
                            </div>
                        </div>
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                            <div class="col-sm-12 col-md-7">
                                <button class="btn btn-primary">@lang('translation.save')</button>
                                <a href="{{ route('post.index') }}" class="btn btn-danger">@lang('translation.cancel')</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script-extra')
    <script src="{{ asset('backend/assets/modules/summernote/summernote-bs4.js') }}"></script>
    <script src="{{ asset('backend/assets/modules/codemirror/lib/codemirror.js') }}"></script>
    <script src="{{ asset('backend/assets/modules/codemirror/mode/javascript/javascript.js') }}"></script>
    <script src="{{ asset('backend/assets/modules/jquery-selectric/jquery.selectric.min.js') }}"></script>
@endsection

resources/views/backend/post/index.blade.php
@extends('backend.layouts.app')
@section('title', @trans('translation.post'))
@section('header', @trans('translation.post'))
@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4>@lang('translation.post')</h4>
                    <div class="card-header-action">
                        <a href="{{ route('post.create') }}" class="btn btn-primary">@lang('translation.create')</a>
                    </div>
                </div>
                <div class="card-body">
                    <table class="table table-striped" id="table-1">
                        <thead>
                            <tr>
                                <th class="text-center">
                                    #
                                </th>
                                <th>@lang('translation.title')</th>
                                <th>@lang('translation.category')</th>
                                <th>@lang('translation.author')</th>
                                <th>@lang('translation.created_at')</th>
                                <th>@lang('translation.action')</th>
                            </tr>
                        </thead>
                        <tbody>
                            {{-- @foreach ($posts as $post)
                                    <tr>
                                        <td>
                                            {{ $loop->iteration }}
                                        </td>
                                        <td>{{ $post->title }}</td>
                                        <td>{{ $post->category->name }}</td>
                                        <td>{{ $post->user->name }}</td>
                                        <td>{{ $post->created_at }}</td>
                                        <td>
                                            <a href="{{ route('post.edit', $post->id) }}" class="btn btn-primary">Edit</a>
                                            <form action="{{ route('post.destroy', $post->id) }}" method="POST"
                                                class="d-inline">
                                                @csrf
                                                @method('delete')
                                                <button type="submit" class="btn btn-danger">Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach --}}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script-extra')
    <script>
        $(document).ready(function() {
            $('#table-1').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('post.index') }}",
                columns: [{
                        data: 'DT_RowIndex',
                        name: 'DT_RowIndex'
                    },
                    {
                        data: 'title',
                        name: 'title'
                    },
                    {
                        data: 'category.name',
                        name: 'category.name'
                    },
                    {
                        data: 'user.name',
                        name: 'user.name'
                    },
                    {
                        data: 'created_at',
                        name: 'created_at',
                        render: function(data) {
                            return moment(data).format('DD MMMM YYYY');
                        }
                    },
                    {
                        data: 'action',
                        name: 'action'
                    },
                ]
            });
        });
    </script>

@endsection